# Probes configuration
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

# -- Optional Pod priorityClassName; leave null to omit the field (default behavior)
priorityClassName: null

config: |
  mqtt:
    host: test.mosquitto.org
    topic_prefix: frigate
  detectors:
    cpu1:
      type: cpu
